default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") %>
  username: <%= ENV.fetch("DB_USER") %>
  password: <%= ENV["DB_PASS"] %>

development:
  <<: *default
  database: petadmin_development

test:
  <<: *default
  database: petadmin_test

production:
  <<: *default
  database: petadmin_production
